# Generated by Django 3.2.3 on 2021-06-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('ogz', models.CharField(max_length=20)),
                ('gender', models.DateField(max_length=2)),
                ('love', models.CharField(max_length=50)),
                ('tel', models.IntegerField(default=0)),
                ('s_time', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
